import polars as pl

TEAM_NAMES = [
    "ATLANTA HAWKS",
    "BOSTON CELTICS",
    "BROOKLYN NETS",
    "CHARLOTTE HORNETS",
    "CHICAGO BULLS",
    "CLEVELAND CAVALIERS",
    "DALLAS MAVERICKS",
    "DENVER NUGGETS",
    "DETROIT PISTONS",
    "GOLDEN STATE WARRIORS",
    "HOUSTON ROCKETS",
    "INDIANA PACERS",
    "LOS ANGELES CLIPPERS",
    "LOS ANGELES LAKERS",
    "MEMPHIS GRIZZLIES",
    "MIAMI HEAT",
    "MILWAUKEE BUCKS",
    "MINNESOTA TIMBERWOLVES",
    "NEW ORLEANS PELICANS",
    "NEW YORK KNICKS",
    "OKLAHOMA CITY THUNDER",
    "ORLANDO MAGIC",
    "PHILADELPHIA 76ERS",
    "PHOENIX SUNS",
    "PORTLAND TRAIL BLAZERS",
    "SACRAMENTO KINGS",
    "SAN ANTONIO SPURS",
    "TORONTO RAPTORS",
    "UTAH JAZZ",
    "WASHINGTON WIZARDS",
    "CHARLOTTE BOBCATS",
    "KANSAS CITY KINGS",
    "NEW JERSEY NETS",
    "NEW ORLEANS HORNETS",
    "NEW ORLEANS/OKLAHOMA CITY HORNETS",
    "SEATTLE SUPERSONICS",
    "ST. LOUIS HAWKS",
    "VANCOUVER GRIZZLIES",
    "WASHINGTON BULLETS",
]

TEAM_ABBREVIATION = [
    "ATL",
    "BOS",
    "BRK",
    "CHO",
    "CHI",
    "CLE",
    "DAL",
    "DEN",
    "DET",
    "GSW",
    "HOU",
    "IND",
    "LAC",
    "LAL",
    "MEM",
    "MIA",
    "MIL",
    "MIN",
    "NOP",
    "NYK",
    "OKC",
    "ORL",
    "PHI",
    "PHO",
    "POR",
    "SAC",
    "SAS",
    "TOR",
    "UTA",
    "WAS",
    "CHA",
    "KCK",
    "NJN",
    "NOH",
    "NOK",
    "SEA",
    "STL",
    "VAN",
    "WSB",
]

active_status = [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,  # Active teams
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,  # Deprecated teams
]


def create_teams_df(
    TEAM_NAMES: list, TEAM_ABBREVIATION: list, active_status: list
) -> pl.DataFrame:
    team_ids = list(range(1, len(TEAM_NAMES) + 1))

    return pl.DataFrame(
        data={
            "id": team_ids,
            "name": TEAM_NAMES,
            "abbreviation": TEAM_ABBREVIATION,
            "active": active_status,
        },
        schema={
            "id": pl.Int32,
            "name": None,
            "abbreviation": None,
            "active": pl.Int8,
        },
    )
